// apps/jam2/src/components/Guest.svelte
<script lang="ts">
	import { appState } from '../State.svelte';
	import { PeerOperationMode } from '../Types/Types';
	import BandJoin from './BandJoin.svelte';
	import SetView from './SetView.svelte';

	// Set peer mode to Guest when this component mounts
	$effect(() => {
		if (appState.store.peerMode !== PeerOperationMode.Guest) {
			appState.setPeerMode(PeerOperationMode.Guest);
		}
	});

	// Check if connected
	let isConnected = $state(false);

	$effect(() => {
		isConnected = !!appState.store.currentSetId;
	});
</script>

<div class="guest-container">
	{#if !isConnected}
		<BandJoin />
	{:else}
		<SetView mode="guest" setId={appState.store.currentSetId} />
	{/if}
</div>

<style>
	.guest-container {
		flex: 1;
		display: flex;
		flex-direction: column;
		margin: 1px;
		padding: 5px;
		overflow-y: auto;
	}
</style>

// apps/old/src/Components/Guest/Guest.tsx
import { dispatch, getStore, pickStore } from '@/Support/Stores/PrimaryStore';
import { ActionType, PeerOperationMode } from '@/Support/Stores/Types';
import { useEffect } from 'react';
import BandJoin from './BandJoin';
import SetView from '../SetList/SetView';
import FollowerService from '../Services/Client/FollowerService';

const Guest = () => {
	const { connectedChannelDetail } = pickStore<'connectedChannelDetail'>();

	useEffect(() => {
		const timeout = setTimeout(() => {
			const store = getStore();
			if (store.peerMode !== PeerOperationMode.Guest) {
				dispatch({type: ActionType.UPDATE, update: {peerMode: PeerOperationMode.Guest}});
			}
		}, 1);

		return () => {
			clearTimeout(timeout);
		}
	}, []);

	return (
		<>
			<FollowerService/>
			<div style={{flex: '1', display: 'flex', flexDirection: 'column', margin: '1px', padding: '5px', overflowY: 'auto'}}>
				{!connectedChannelDetail && <BandJoin/>}
				{connectedChannelDetail && <SetView mode={PeerOperationMode.Guest} />}
			</div>
		</>
	)
}

export default Guest;
