// apps/old/src/Components/Services/MessageChannelService.tsx
import { getStore } from '@/Support/Stores/PrimaryStore';
import { useQuery } from '@tanstack/react-query';
import { LogError, LogInfo } from '@shared/services/Logger';
import { Messages } from '@shared/services/syncuprocks/musician/MessageQueue';
import { PeerOperationMode } from "@/Support/Stores/Types";
import { MessageBusActionType } from '@/Types/MessageBus';
import { BroadcastMessage } from '@/Support/Stores/MessageBus';

const MessageChannelService = () => {
	useQuery({
		queryKey: ['my.messages'],
		queryFn: async () => {
			const store = getStore();
			if (!store || !store.user || store.peerMode === PeerOperationMode.Solo) {
				LogError('MessageChannelService: No store|user|invalid peer mode');
				return;
			}

			const response = await Messages.getMessages();
			if (response.length > 0) {
				LogInfo(`MessageChannelService: Rx'd ${response.length} new messages`);
				BroadcastMessage({data: {type: MessageBusActionType.MESSAGE, message: response}})
			}
			return response;
		},
		refetchInterval: 1000,
		staleTime: 0,
		// TODO ??? cacheTime: 0,
		retry: 0,
		refetchOnMount: false,
		refetchOnWindowFocus: false,
		enabled: true,
		refetchIntervalInBackground: true,
	});

	return (
		<></>
	)
}

export default MessageChannelService;

// apps/jam2/src/components/Services/MessageChannelService.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { createQuery } from '@tanstack/svelte-query';
	import { appState } from '../../State.svelte';
	import { PeerOperationMode } from '../../Types/Types';
	import { messageBus } from '../../Support/MessageBus';

	let lastMessageTime = $state(null);

	// Placeholder MessageChannelService - polls for messages
	const query = createQuery({
		queryKey: ['my.messages'],
		queryFn: async () => {
			if (!appState.store.user || appState.store.peerMode === PeerOperationMode.Solo) {
				return [];
			}

			// TODO: Implement Messages.getMessages()
			console.log('Polling for messages...');
			lastMessageTime = new Date().toLocaleTimeString();
			return [];
		},
		refetchInterval: 1000,
		staleTime: 0,
		refetchOnMount: false,
		refetchOnWindowFocus: false,
		enabled: !!appState.store.user && appState.store.peerMode !== PeerOperationMode.Solo,
	});
</script>

{#if appState.store.peerMode !== PeerOperationMode.Solo}
	<div class="message-channel-service">
		<h4>Message Channel Service</h4>
		<p>Status: {query.isFetching ? 'Polling...' : 'Idle'}</p>
		<p>Last poll: {lastMessageTime || 'Never'}</p>
		<p>Messages: {query.data?.length || 0}</p>
		<!-- TODO: Process messages and send to MessageBus -->
	</div>
{/if}

<style>
	.message-channel-service {
		padding: 1rem;
		border: 1px solid #ccc;
		border-radius: 0.5rem;
		margin: 1rem 0;
	}
</style>
