// apps/jam2/src/components/HostModeStatus.svelte
<script lang="ts">
	import { appState } from '../State.svelte';
	import { PeerOperationMode } from '../Types/Types';
	import { LogInfo } from '@shared/services/Logger';
	import { broadcastMessage } from '../Support/MessageBus';
	import { MessageBusActionType } from '../Types/MessageBus';

	let show = $state(false);

	function bootFromBand(user: any) {
		LogInfo(`Kicking User:Instance (${user.username} out of band!)`);
		broadcastMessage({
			data: {
				type: MessageBusActionType.KICKOUT,
				userId: user.userId,
				instance: ''
			}
		});
		setShow(false);
	}

	function setShow(value: boolean) {
		show = value;
	}
</script>

{#if appState.store.peerMode === PeerOperationMode.Host}
	<button
		class="status-button"
		onclick={() => setShow(!show)}
		title="Host Status"
		aria-label="Host status menu"
	>
		🎸
	</button>

	{#if show}
		<div class="status-overlay" onclick={() => setShow(false)} onkeydown={(e) => { if (e.key === 'Escape') setShow(false); }} role="dialog" aria-modal="true" tabindex="-1">
			<div class="status-popover" onclick={(e) => e.stopPropagation()}>
				<div class="status-header">
					<h4>Band Leader {appState.store.user?.displayName}</h4>
					<button onclick={() => setShow(false)} aria-label="Close">&times;</button>
				</div>
				<div class="status-body">
					<div class="bandmates-section">
						<strong>Bandmates:</strong>
						{#if appState.store.connectedUsers.length > 0}
							<ul class="bandmates-list">
								{#each appState.store.connectedUsers as user (user.userId)}
									<li class="bandmate-item">
										{user.username} ({user.role})
										<button
											class="kick-button"
											onclick={() => bootFromBand(user)}
											aria-label="Kick {user.username} out of band"
										>
											Kick out
										</button>
									</li>
								{/each}
							</ul>
						{:else}
							<p>No bandmates connected</p>
						{/if}
					</div>
				</div>
			</div>
		</div>
	{/if}
{/if}

<style>
	.status-button {
		background: none;
		border: none;
		color: white;
		cursor: pointer;
		font-size: 1.5rem;
		padding: 0.5rem;
		border-radius: 0.25rem;
		transition: background-color 0.2s;
	}

	.status-button:hover {
		background-color: rgba(255, 255, 255, 0.1);
	}

	.status-overlay {
		position: fixed;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		background-color: rgba(0, 0, 0, 0.5);
		display: flex;
		justify-content: center;
		align-items: center;
		z-index: 1000;
	}

	.status-popover {
		background: white;
		border-radius: 0.5rem;
		max-width: 400px;
		width: 90%;
		box-shadow: 0 4px 15px rgba(0, 0, 0, 0.3);
	}

	.status-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: 1rem;
		border-bottom: 1px solid #dee2e6;
		background-color: #f8f9fa;
		border-radius: 0.5rem 0.5rem 0 0;
	}

	.status-header h4 {
		margin: 0;
		font-size: 1.1rem;
	}

	.status-header button {
		background: none;
		border: none;
		font-size: 1.5rem;
		cursor: pointer;
		padding: 0;
		width: 2rem;
		height: 2rem;
		display: flex;
		align-items: center;
		justify-content: center;
		border-radius: 50%;
		transition: background-color 0.2s;
	}

	.status-header button:hover {
		background-color: rgba(0, 0, 0, 0.1);
	}

	.status-body {
		padding: 1rem;
	}

	.bandmates-section {
		margin-bottom: 1rem;
	}

	.bandmates-list {
		list-style: none;
		padding: 0;
		margin: 0.5rem 0 0 0;
	}

	.bandmate-item {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: 0.5rem 0;
		border-bottom: 1px solid #eee;
	}

	.bandmate-item:last-child {
		border-bottom: none;
	}

	.kick-button {
		background-color: #dc3545;
		color: white;
		border: none;
		padding: 0.25rem 0.5rem;
		border-radius: 0.25rem;
		cursor: pointer;
		font-size: 0.875rem;
		transition: background-color 0.2s;
	}

	.kick-button:hover {
		background-color: #c82333;
	}
</style>

// apps/jam/src/Components/Header/HostModeStatus.tsx
import { useRef, useState } from 'react'
import { pickStore } from '@/Support/Stores/PrimaryStore';
import { HostModeStatusIcon } from '@/Constants/AppIcons';
import { Button } from 'react-bootstrap';
import Overlay from 'react-bootstrap/Overlay';
import Popover from 'react-bootstrap/Popover';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { ConnectedUser } from '@/Support/Stores/Types';
import { BroadcastMessage } from '@/Support/Stores/MessageBus';
import { MessageBusActionType } from '@/Types/MessageBus';
import { LogInfo } from '@shared/services/Logger';

const HostModeStatus = () => {
	const { user, connectedUsers } = pickStore<'user'|'connectedUsers'>();

	const profileTarget = useRef(null);
	const [show, setShow] = useState(false);

	const bootFromband = (u: ConnectedUser) => {
		LogInfo(`Kicking User:Instance (${u.username} out of band!)`);
		BroadcastMessage({data: { type: MessageBusActionType.KICKOUT, userId: u.userId, instance: '' }});
		setShow(false);
	};

	return (
		<>
			<Button ref={profileTarget} onClick={() => setShow(!show)} variant='link'>
				<FontAwesomeIcon icon={HostModeStatusIcon} size='2x' />
			</Button>
			<Overlay
				show={show}
				target={profileTarget}
				placement="bottom"
				containerPadding={5}
				rootClose={true}
				onHide={() => setShow(false)}
			>
				<Popover id="popover-contained">
					<Popover.Header as="h3">Band Leader {user!.displayName}</Popover.Header>
					<Popover.Body>
						<div style={{display: 'flex', flexDirection: 'column', columnGap: '10px', rowGap: '10px'}}>
							<div><b>Bandmates: </b>
								<ul>
									{ connectedUsers.map((u) =>
										(<li key={`${u.username}`}>{`${u.username} (${u.role})`} <Button onClick={() => bootFromband(u)} variant='danger'>Kick out of band!</Button></li>)
									)}
								</ul>
							</div>
						</div>
					</Popover.Body>
				</Popover>
			</Overlay>
		</>
	)
}

export default HostModeStatus
