// apps/jam/src/components/SetView.svelte
<script lang="ts">
	import { createQuery } from '@tanstack/svelte-query';
	import { router } from '../Router.svelte';
	import { appState } from '../State.svelte';
	import { PeerOperationMode, SongPlayStatus } from '../Types/Types';
	import { Log, LogVerbose } from '@shared/services/Logger';
	import SongView from './SongView.svelte';
	import { getSongStore } from '../Support/Stores/SongStore';

// Placeholder types - TODO: import from shared
interface SetComplete {
	musicianId: number;
	id: number;
	name: string;
	createdAtMsUtc: number;
	songs: any[]; // Song[]
}

interface ApiResponseBase<T> {
	success: boolean;
	data?: T;
	errorMessage?: string;
}

	interface Props {
		mode: 'host' | 'solo';
		setId: string;
	}

	let { mode, setId }: Props = $props();

	// Update state
	$effect(() => {
		const peerMode = mode === 'host' ? PeerOperationMode.Host : PeerOperationMode.Solo;
		appState.setPeerMode(peerMode);
		appState.setCurrentSet(parseInt(setId, 10));
	});

	const query = createQuery({
		queryKey: ['setlist', appState.store.currentSetId],
		queryFn: async () => {
			if (!appState.store.currentSetId) return null;
			LogVerbose(`Downloading set overview for setId=${appState.store.currentSetId}`);
			const data = await fetch(`/api/legacy/user/sets/complete/${appState.store.currentSetId}`, {
				method: "GET",
				headers: { "Content-Type": "application/json" }
			});
			const response: ApiResponseBase<SetComplete> = await data.json();
			return response.data;
		},
		refetchInterval: false,
		staleTime: 0,
		refetchOnMount: 'always',
		refetchOnWindowFocus: false,
		enabled: !!appState.store.currentSetId,
	});

	// Auto-select first song when set loads
	$effect(() => {
		if ($query.data && $query.data.songs.length > 0 && !appState.store.currentSongId) {
			appState.updateStore({ currentSongId: $query.data.songs[0].id });
		}
	});

	function loadSong(song: any) {
		appState.updateStore({
			currentSongId: song.id,
			songPlayStatus: SongPlayStatus.Play
		});
	}

	function playSong() {
		appState.updateStore({ songPlayStatus: SongPlayStatus.Play });
	}

	function pauseSong() {
		appState.updateStore({ songPlayStatus: SongPlayStatus.Pause });
	}

	function formatDuration(duration: number): string {
		const totalSeconds = Math.floor(duration / 1000);
		const mins = Math.floor(totalSeconds / 60);
		const secs = totalSeconds % 60;
		return `${mins}:${secs.toString().padStart(2, '0')}`;
	}
</script>

<div class="set-view">
	{#if $query.isLoading}
		<div>Loading set...</div>
	{:else if $query.data}
		<div class="set-container">
			<!-- Sidebar with controls and song list -->
			<div class="sidebar">
				<div class="controls">
					<button
						class="control-btn play-btn"
						class:pulse={appState.store.songPlayStatus === SongPlayStatus.Play}
						onclick={playSong}
						title="Start playing"
					>
						▶
					</button>
					<button
						class="control-btn"
						onclick={pauseSong}
						title="Pause Playback"
					>
						⏸
					</button>
					<button
						class="control-btn"
						onclick={pauseSong}
						title="Next"
					>
						⏭
					</button>
				</div>

				<div class="song-list">
					<ul>
						{#each $query.data.songs as song (song.id)}
							<li>
								<button
									class="song-btn"
									class:active={appState.store.currentSongId === song.id}
									onclick={() => loadSong(song)}
									title={`Play ${song.title || song.name || 'Untitled'}`}
								>
									▶ {song.title || song.name || 'Untitled'}
								</button>
							</li>
						{/each}
					</ul>
				</div>
			</div>

			<!-- Main content area -->
			<div class="main-content">
				{#if appState.store.currentSongId}
					<SongView
						song={$query.data.songs.find(s => s.id === appState.store.currentSongId)}
						mode={mode}
					/>
				{:else}
					<div class="no-song">Select a song to begin</div>
				{/if}
			</div>
		</div>
	{:else}
		<div>No set data</div>
	{/if}

	<button class="back-btn" onclick={() => router.navigate(mode === 'host' ? 'HostSets' : 'SoloSets')}>
		Back to Sets
	</button>
</div>

<style>
	.set-view {
		position: relative;
		height: 100vh;
		display: flex;
		flex-direction: column;
	}

	.back-btn {
		position: absolute;
		bottom: 10px;
		right: 10px;
		padding: 0.5rem 1rem;
		background-color: #6c757d;
		color: white;
		border: none;
		border-radius: 0.25rem;
		cursor: pointer;
		z-index: 10;
	}

	.back-btn:hover {
		background-color: #5a6268;
	}

	.set-container {
		display: flex;
		flex: 1;
		height: calc(100vh - 60px); /* Account for navbar */
	}

	.sidebar {
		width: 200px;
		background: rgba(0, 0, 0, 0.8);
		display: flex;
		flex-direction: column;
		border-right: 1px solid rgba(255, 255, 255, 0.3);
	}

	.controls {
		padding: 10px;
		border-bottom: 1px solid rgba(255, 255, 255, 0.3);
		display: flex;
		gap: 5px;
		justify-content: center;
	}

	.control-btn {
		padding: 8px 15px;
		background-color: #343a40;
		color: white;
		border: none;
		border-radius: 4px;
		cursor: pointer;
		font-size: 1.2rem;
	}

	.control-btn:hover {
		background-color: #495057;
	}

	.play-btn.pulse {
		animation: pulse 1s infinite;
	}

	@keyframes pulse {
		0% { opacity: 1; }
		50% { opacity: 0.7; }
		100% { opacity: 1; }
	}

	.song-list {
		flex: 1;
		overflow-y: auto;
		padding: 10px 0;
	}

	.song-list ul {
		list-style: none;
		margin: 0;
		padding: 0;
	}

	.song-list li {
		margin: 2px 0;
	}

	.song-btn {
		width: 100%;
		padding: 8px 10px;
		background-color: #343a40;
		color: white;
		border: none;
		text-align: left;
		cursor: pointer;
		font-size: 0.9rem;
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
		border-radius: 0;
	}

	.song-btn:hover {
		background-color: #495057;
	}

	.song-btn.active {
		background-color: rgba(100, 100, 200, 0.8);
	}

	.main-content {
		flex: 1;
		background: rgba(255, 255, 255, 0.1);
		display: flex;
		flex-direction: column;
	}

	.no-song {
		display: flex;
		align-items: center;
		justify-content: center;
		height: 100%;
		color: white;
		font-size: 1.2rem;
	}
</style>

// apps/jam/src/Components/SetList/SetView.tsx
import { PlayIcon, PauseIcon, SkipIcon } from "@/Constants/AppIcons";
import { dispatch, pickStore } from "@/Support/Stores/PrimaryStore";
import { ActionType, PeerOperationMode, SongPlayStatus } from "@/Support/Stores/Types";
import { Log, LogError, LogInfo, LogVerbose } from "@/Support/Utilities/Logger";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useQuery } from "@tanstack/react-query";
import { useEffect } from "react";
import { Button } from "react-bootstrap";
import { useParams } from "react-router";
import { SongOverview, SetComplete, TrackFormat } from "@shared/services/syncuprocks/musician/Types";
import SongView from "./SongView";
import { ApiResponseBase } from "./Types";
import { getSongStore } from "@/Support/Stores/SongStore";

interface IProp {
	mode: PeerOperationMode
}

const SetView = ({mode}:IProp) => {
	const { currentSetId, currentSongId, songPlayStatus, connectedChannelDetail } = pickStore<'currentSetId'|'currentSongId'|'songPlayStatus'|'connectedChannelDetail'>();
	const { setId } = useParams();
	const songStore = getSongStore();

	useEffect(() => {
		const timeout = setTimeout(() => {
			if (mode !== PeerOperationMode.Guest) {
				dispatch({type: ActionType.UPDATE, update: {currentSetId: parseInt(setId!, 10), peerMode: mode}});
			}
		}, 1);

		return () => {
			clearTimeout(timeout);
		}
	}, [mode, setId, currentSetId]);

	const { data, isLoading } = useQuery({
		queryKey: ['setlist', currentSetId],
		queryFn: async () => {
			LogVerbose(`Downloading set overview for setId=${currentSetId} host=${connectedChannelDetail?.hostUser ?? 'none'}`);
			const data = await fetch(`/api/legacy/user/sets/complete/${currentSetId}`, { method: "GET", headers: { "Content-Type": "application/json" }});
			const response: ApiResponseBase<SetComplete> = await data.json();

			return response.data;
		},
		refetchInterval: false,
		staleTime: 0,
		// TODO: ?? cacheTime: 60000,
		refetchOnMount: 'always',
		refetchOnWindowFocus: false,
		enabled: currentSetId !== undefined,
	});

	const { data: trackData, isLoading: loadingTracks } = useQuery({
		queryKey: ['song.track', currentSongId],
		queryFn: async () => {
			if (!data) {
				throw Error('Invalid Set State');
			}

			const set = data;
			const song = currentSongId;
			const songDetails = set.songs.find((s) => s.id === song);
			if (!songDetails) {
				throw Error(`Invalid Set State - song ${song} not found in set ${set.id}`);
			}

			songDetails.tracks.forEach(async (t) => {
				// Check if file already found...
				if (!(await songStore.exists(song!, t.id))) {
					LogInfo(`Downloading track information for ${set.id}/${song}/${t.id} ${t.name}`);
					let trackUrl = `/api/legacy/user/song/track/${currentSetId}/${t.id}/data`;
					if (t.format === TrackFormat.Lyric) {
						const trackResponse = await fetch(trackUrl, { method: "GET", headers: { 'pragma': 'no-cache', 'cache-control': 'no-store', 'cache': 'no-store' }});
						if (trackResponse.ok) {
							const track = await trackResponse.blob();
							if (!data) {
								throw Error(`Invalid Set Track '${song}' - no track data!`);
							}

							LogInfo(`Downloaded ${trackUrl}`);
							await songStore.put({
								data: track,
								format: t.format,
								songId: song!,
								trackId: t.id,
								timestamp: 1
							})
						}
					} else {
						LogError(`Unsupported Track Format: ${t.format}`);
					}
				} else {
					Log('verbose', `Found in cache: ${set.id}/${song}/${t.id} ${t.name}`);
				}
			});

			return songDetails;
		},
		staleTime: Infinity,
		// TODO: cacheTime: Infinity,
		refetchOnMount: false,
		refetchOnWindowFocus: false,
		enabled: currentSongId !== undefined && data != null,
	});

	useEffect(() => {
		if (!data) {
			return;
		}

		if (data.songs.length === 0) {
			dispatch({type: ActionType.UPDATE, update: {currentSongId: undefined}});
		} else {
			dispatch({type: ActionType.UPDATE, update: {currentSongId: data.songs[0].id}});
		}
	}, [data])

	useEffect(() => {
		// Note, must be secure context (https/localhost) to use
		// chrome://flags/#unsafely-treat-insecure-origin-as-secure
		// TODO: handle visibility switch - reenable (or pause playback)
		if (!navigator.wakeLock) {
			Log('error', 'navigator.wakeLock not available');
			return;
		}
		
		let wake: WakeLockSentinel | undefined;
		if (songPlayStatus === SongPlayStatus.Play) {
			navigator.wakeLock.request('screen').then((wl) => {
				wake = wl;
				Log('info', 'WakeLock acquired');
			})
			.catch((e) => {
				Log('error', `WakeLock.request failed: ${e}`);
			});
		}

		return () => {
			if (wake) {
				wake.release().then(() => {
					wake = undefined;
					Log('info', 'WakeLock released');
				})
				.catch((e) => Log('error', `WakeLock.release failed: ${e}`));
			}
		}
	}, [songPlayStatus]);

	if (isLoading) {
		return <>Loading Set...</>
	}

	if (!currentSongId) {
		return <></>
	}

	const loadSong = (song: SongOverview) => {
		dispatch({type: ActionType.UPDATE, update: {currentSongId: song.id, songPlayStatus: SongPlayStatus.Play}});
	};

	const playSong = () => {
		dispatch({type: ActionType.UPDATE, update: {songPlayStatus: SongPlayStatus.Play}});
	};

	const pauseSong = () => {
		dispatch({type: ActionType.UPDATE, update: {songPlayStatus: SongPlayStatus.Pause}});
	};

	const currentSet = data!;
	const song = currentSongId && data ? data.songs.find((x) => x.id === currentSongId) : undefined;

	return (
		<div style={{flex: '1', display: 'flex', flexDirection: 'row', margin: '1px', padding: '2px', overflowY: 'auto'}}>
			<div style={{width: '195px', background: 'rgba(0,0,0,.5)', display: 'flex', flexDirection: 'column'}}>
				<div style={{padding: '2px 2px 10px', borderBottom: '1px solid rgba(255,255,255,.5)'}}>
					<Button style={{margin: '2px', padding: '5px 19px'}} className={songPlayStatus === SongPlayStatus.Play ? 'pulse' : 'inherit'} variant='dark' onClick={() => playSong()} title={'Start playing'}>
						<FontAwesomeIcon icon={PlayIcon} size='lg'/>
					</Button>
					<Button style={{margin: '2px', padding: '5px 19px'}} variant='dark' onClick={() => pauseSong()} title={'Pause Playback'}>
						<FontAwesomeIcon icon={PauseIcon} size='lg'/>
					</Button>
					<Button style={{margin: '2px', padding: '5px 19px'}} variant='dark' onClick={() => pauseSong()} title={'Next'}>
						<FontAwesomeIcon icon={SkipIcon} size='lg'/>
					</Button>
				</div>
				
				<div style={{flex: 'auto', overflowX: 'hidden', overflowY: 'auto', color: 'white', padding: '20px 0px'}}>
					<ul style={{margin: '0', padding: '0'}}>
						{currentSet.songs.map((s) => {
							return <li key={s.id}>
								{/* TODO: Show current song, and queued song {background: currentSongId === s.id ? 'rgba(100,100,200,.8) */}
								<div style={{overflow: 'hidden', userSelect: 'none', whiteSpace: 'nowrap', padding: '2px 5px 2px 4px'}}>
									<Button style={{padding: '4px', margin: '1px 0px', width: '100%', textOverflow: 'ellipsis', textAlign: 'start', overflow: 'clip'}} variant='dark' title={`Play ${s.name}`} onClick={() => loadSong(s)} size='lg'>
										<FontAwesomeIcon icon={PlayIcon} size='lg'/>
										{` ${s.name}`}
									</Button>
								</div>
							</li>
						})}
					</ul>
				</div>
			</div>

			<div style={{ flex: '1', background: 'rgba(255,255,255,.2'}}>
				{loadingTracks && (<div>{`Loading Song ${currentSongId}...`}</div>)}
				{trackData && song && (
					<SongView song={song} tracks={trackData.tracks} key={song.id}/>
				)}
			</div>
		</div>
	)
};

export default SetView;
